require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require 'date'
require_relative '../lib/key'
require_relative '../lib/enigma'
require_relative '../lib/generate_date'
require_relative '../lib/shift'
